### ISSUE TITLE
How lazy is listBits?

### ISSUE THREAD

**Issue by kozross** [Bodigrim/bitvec#27]
I know I could read the source code, but the implementation appears quite involved. My specific question relates to code like

```haskell
take 3 . listBits $ vec
```

where ``vec`` has 100+ set bits. Will this immediately generate a list of 100 bits, or will it only generate the 3 needed?

**Comment by Bodigrim** [comment]
`listBits` boils down to a right fold, so it is as lazy as possible:

```haskell
listBitsInWords :: Int -> P.Vector Word -> [Int] -> [Int]
listBitsInWords offset = flip $ 
  Data.Vector.Primitive.ifoldr -- right fold with a lazy accumulator
    (\i word acc -> listBitsInWord (offset + mulWordSize i) word ++ acc)
```

**Comment by kozross** [comment]
Awesome, thank you!
