### ISSUE TITLE
Add F2Poly extended Euclidean algorithm

### ISSUE THREAD

**Issue by Multramate** [Bodigrim/bitvec#30]
An analogue of `gcdExt` for `F2Poly` similar to that of `Poly`. Would also be convenient to have relevant `Semiring` instances to use `gcd`, etc.

**Comment by Bodigrim** [comment]
I have decided against depending on `semirings`. The thing is that `F2Poly` is kinda side gig, and I want to keep dependency profile of `bitvec` as low as possible. By virtue of having `Integral F2Poly` instance, `WrappedIntegral F2Poly` should fit into `Semirings` hierarchy well.

I do not mind `gcdExt` here, but maybe it is time to add a generic implementation to `semirings`? Like 

```haskell
gcdExt :: (Euclidean a, Ring a) => a -> a -> (a, a)
```

**Comment by Multramate** [comment]
Thanks - will start adding `gcdExt`.

I agree on the generic implementation, but it will be for another day.
