### ISSUE TITLE
Add F2Poly pretty Show instance

### ISSUE THREAD

**Issue by Multramate** [Bodigrim/bitvec#32]
Rather than having to see `F2Poly {unF2Poly = [..]}` constantly, we could have a pretty Show instance just like in `poly`.

**Comment by Bodigrim** [comment]
Good point. The attraction of `Show (Poly v a)` instance comes from the fact that it prints a valid Haskell expression with the same value, which requires pattern synonym `X` is scope. It also seems that in case of binary polynomials `1 * X^4 + 0 * X^3 + 1 * X^2 + 0 * X + 1` is too verbose.

As long as the easiest way to construct `F2Poly` is using binary literals, I would prefer `Show` instance to print a binary literal as well. E. g., 

```haskell
> gcdExt 0b11 0b111
(0b1,0b10)
```

What do you think about it?

**Comment by Multramate** [comment]
Looks good and clean - will try to do that now.

**Comment by Bodigrim** [comment]
Closed in #33.
