### ISSUE TITLE
Convert to Data.Vector.Storable Word8 and back

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/bitvec#34]
I've been asked a couple of times about interacting with `ByteString`. I really do not want to add `bytestring` as dependency, so hopefully casting to storable vectors would be a reasonable half-measure.

**Comment by kozross** [comment]
Is there a reason you don't want ``bytestring`` as a dependency? You depend on ``semigroups``, which already drags it in transitively.

**Comment by Bodigrim** [comment]
We depend on `semigroups` only when building against GHC 7.10:
https://github.com/Bodigrim/bitvec/blob/a218e10afc4730fa15cb4100036e8c2b235d0049/bitvec.cabal#L83-L85

Writing `foo :: ByteString -> BitVec` implies not only dependency on `bytestring` _per se_, but involves fiddling with internals of `Data.ByteString.Internal`, which is unstable and unsafe. I would like to avoid this, given that `ByteString` is kinda side gig for this package.

**Comment by kozross** [comment]
@Bodigrim Thanks for clarifying. Yeah, in that case, a vector-of-bytes conversion should be fine.
