### ISSUE TITLE
Issue building bitvec on Windows

### ISSUE THREAD

**Issue by newhoggy** [Bodigrim/bitvec#41]
When compiling `hw-dsv` on Windows, there was an issue trying to link `bitvec`, which is one of the dependencies:

```
C:\Users\newho\wrk\hw-dsv>cabal build --ghc-options=-v
...
"C:\ProgramData\chocolatey\lib\ghc.8.6.5\tools\ghc-8.6.5\lib\../mingw/bin/gcc.exe" "-fno-stack-protector" "-DTABLES_NEXT_TO_CODE" "--print-search-dirs"
Loading package ghc-prim-0.5.3 ... linking ... done.
Loading package integer-gmp-1.0.2.0 ... linking ... done.
Loading package base-4.12.0.0 ... linking ... done.
Loading package array-0.5.3.0 ... linking ... done.
Loading package deepseq-1.4.4.0 ... linking ... done.
Loading package transformers-0.5.6.2 ... linking ... done.
Loading package primitive-0.7.1.0 ... linking ... done.
Loading package vector-0.12.1.2 ... linking ... done.
Loading package bits-extra-0.0.2.0 ... linking ... done.
Loading package bytestring-0.10.8.2 ... linking ... done.
Loading package bitvec-1.0.3.0 ... ghc.exe: Could not load `libgmp-10.dll'. Reason: addDLL: libgmp-10.dll or dependencies not loaded. (Win32 error 126)

*** Deleting temp files:
Deleting: C:\Users\newho\AppData\Local\Temp\ghc1656_0\ghc_1.hscpp
*** Deleting temp dirs:
Deleting: C:\Users\newho\AppData\Local\Temp\ghc1656_0
ghc.exe: panic! (the 'impossible' happened)
  (GHC version 8.6.5 for x86_64-unknown-mingw32):
        loadArchive "C:\\ProgramData\\chocolatey\\lib\\ghc.8.6.5\\tools\\ghc-8.6.5\\mingw\\lib\\libgmp.dll.a": failed

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

cabal.exe: Failed to build hw-dsv-0.4.1.0 (which is required by exe:hw-dsv
from hw-dsv-0.4.1.0).
```

**Comment by newhoggy** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/issues/18556

**Comment by hsyl20** [comment]
libgmp is bundled with GHC on Windows (in-tree GMP build).

@Bodigrim perhaps make `libgmp` flag defaults to False on Windows?

**Comment by Bodigrim** [comment]
It feels weird to mutilate Windows users just because Chocolatey does not add `$GHC/mingw/bin` to `$PATH`. I mean, `stack` works perfectly fine, and manually downloaded GHC with correct `$PATH` works as well. Let me get back from holidays and take a closer look next week.

**Comment by Bodigrim** [comment]
@newhoggy what is the scope of affected systems here? How difficult is to extend `$PATH` or maybe to set `bitvec:libgmp` flag to `False` there? I'm sorry, I've never used Chocolatey, prefering either to set up GHC manually or to let `stack` to manage it, and do not have much idea how widespread Chocolatey is.

**Comment by Bodigrim** [comment]
Given GHC's gradual drift away from GMP, it probably becomes unwise to assume that `libgmp` is available. I'll make this flag `False` by default.

**Comment by Bodigrim** [comment]
Flag `libgmp` will be disabled by default in the next release.

**Comment by newhoggy** [comment]
FYI, there has been an update in this ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/18556#note_308417

Might be worth documenting.

Also I've had some success building on Windows with Github Actions, so it might be worth, getting that running for this project to verify it is all working fine.

**Comment by Bodigrim** [comment]
@newhoggy setting up a Windows build for `bitvec` would be much appreciated. Unfortunately, I myself do not have any experience with GitHub actions or AppVeyor.

What exactly are you suggesting to document?

**Comment by Mistuke** [comment]
> It feels weird to mutilate Windows users just because Chocolatey does not add $GHC/mingw/bin to $PATH. I mean, stack works perfectly fine, and manually downloaded GHC with correct $PATH works as well. Let me get back from holidays and take a closer look next week.

This is fundamental lack of understanding. By doing this you're mixing the libgmp of the compiler and that of the environment it's in. Chocolatey doesn't put the bin on the PATH because doing so is wrong. Secondly linking against a dll instead of the import library again shows a fundamental misunderstanding of linking on Windows.

**Comment by Bodigrim** [comment]
I'm happy to admit my fundamental lack of understanding :) Thanks for detailed explanation. 

This package does not expect `libgmp` to be available by default any more, and `README` has been updated to suggest installing it via `pacman`.

**Comment by Mistuke** [comment]
Cheers :) and my apologies if my reply came over a bit harsh.  The packaging routinely gets blamed for doing the right thing :(
