### ISSUE TITLE
Support thread safe unsafeWrite

### ISSUE THREAD

**Issue by Bodigrim** [Bodigrim/bitvec#5]
Current `unsafeWrite` (consisting internally of `read` and `write`) is not thread safe, as demonstrated by the following program:

```haskell
module Main where

import Control.Concurrent
import Control.Monad
import Control.Monad.Primitive
import Data.Bit
import Data.Foldable
import qualified Data.Vector.Unboxed as V
import qualified Data.Vector.Unboxed.Mutable as MV

len :: Int
len = 1000

foo :: MV.MVector (PrimState IO) Bit -> [Int] -> IO ()
foo vec = traverse_ $ \x -> MV.write vec x (Bit True)

main :: IO ()
main = forever $ do
  m <- newEmptyMVar
  vec <- MV.new len
  forkIO $ do
    foo vec [0,2..len-1]
    putMVar m ()
  foo vec [1,3..len-1]
  takeMVar m
  wec <- V.unsafeFreeze vec
  if V.all (== Bit True) wec
    then putStr "."
    else putStr "!"
```

One can write a thread-safe implementation using [`fetchAndIntArray`](http://hackage.haskell.org/package/ghc-prim-0.5.3/docs/GHC-Prim.html#v:fetchAndIntArray-35-) and [`fetchOrIntArray`](http://hackage.haskell.org/package/ghc-prim-0.5.3/docs/GHC-Prim.html#v:fetchOrIntArray-35-).

It remains to be benchmarked whether it makes sense to make thread-safe implementation default one or provide both safe and unsafe newtypes.

**Comment by treeowl** [comment]
For the thread-safe version, you should be able to import `Data.Vector.Unboxed.Base` to convert, for free, between `Unboxed` vectors of words and `Primitive` vectors of words. Then you can use whatever atomic operations are offered by `primitive`, and/or whatever else you need from `GHC.Prim` (as re-exported from `GHC.Exts`).

**Comment by Bodigrim** [comment]
My draft looks as follows:

```haskell
basicUnsafeWrite (BitMVec s _ (U.MV_Word (P.MVector o _ (MutableByteArray mba)))) !i' (Bit True) = do
    let i     = s + i'
        I# j  = o + divWordSize i
        k     = modWordSize i
        I# kk = 1 `unsafeShiftL` k
    primitive $ \s ->
        let (# s', _ #) = fetchOrIntArray# mba j kk s in
            (# s', () #)
```

This thread-safe implementations appears to be almost twice slower than unsafe one, so I think it is worth to wrap it into its own newtype. I am not sure which of two should be provided to users as "default".

**Comment by Bodigrim** [comment]
Done.
