### ISSUE TITLE
`setBit` and `clearBit` do not work as expected

### ISSUE THREAD

**Issue by fryguybob** [Bodigrim/bitvec#55]
```haskell
ghci> [0,0,0,1] `setBit` 1 :: Vector Bit
[0,1]
```

I think this happens because the `zipWith` function works over the minimum of the lengths and `setBit` is default implemented as `bit i .|. x`.  I would expect the result to have the length of `x` here.

**Comment by Bodigrim** [comment]
Ah, good catch!

**Comment by Bodigrim** [comment]
This is fixed now, thanks!
