### ISSUE TITLE
Unpack vectors

### ISSUE THREAD

**Issue by treeowl** [Bodigrim/bitvec#6]
Currently,

```haskell
data instance U.MVector s Bit = BitMVec !Int !Int !(U.MVector s Word)
data instance U.Vector    Bit = BitVec  !Int !Int !(U.Vector    Word)
```

A vector or mutable vector is two unboxed `Int`s and a pointer to a `U.(M)Vector`, which itself is two unboxed `Int`s and a pointer to a raw byte array. I'd expect you'd be better off with

```haskell
data instance U.MVector s Bit = BitMVec !Int !Int {-# UNPACK #-} !(U.MVector s Word)
data instance U.Vector    Bit = BitVec  !Int !Int {-# UNPACK #-} !(U.Vector    Word)
```

which gets rid of one indirection. You'd have to check that it doesn't interfere with stream fusion somehow in the immutable case.

**Comment by Bodigrim** [comment]
Thanks for suggestion. Is there a recommended way to check an effect on stream fusion?

**Comment by Bodigrim** [comment]
Done.
