### ISSUE TITLE
The zipBits type is unsafe

### ISSUE THREAD

**Issue by treeowl** [Bodigrim/bitvec#76]
The argument function has type `forall a. Bits a => a -> a -> a`. This is insufficient to avoid bad behavior. Nothing stops the function from performing shifts, rotations, `popCount`, `bitSizeMaybe`, `setBit`, etc. In principle, we'd be safe if we had a superclass of `Bits` that just supported the operations we want, but that's not the case. Options:

1. Make a newtype around `Word` whose `Bits` instance errors out for unsupported operations, and make the argument function deal with that type. This seems like the easiest thing. It should be moderately easy to document the restrictions. I believe the supported operations are `.|.`, `.&.`, `xor`, `complement` and `zeroBits`. I suppose `isSigned` could be supported too, but it would be quite useless.
2. Use a newtype around `Word` without a `Bits` instance, and make the user use custom operators.
3. Just give each operation a different name, and forget about the general `zipBits`.

**Comment by Bodigrim** [comment]
It could be just `Bit -> Bit -> Bit` or `Bool -> Bool -> Bool`.

**Comment by treeowl** [comment]
`Bit -> Bit -> Bit` seems most logical, and `Bool -> Bool -> Bool` seems most convenient. The main downside I see is that those don't work with a nifty little trick to cut down the size of `zipBits`. With the current type, instead of using `f False False`, `f False True`, etc., and inspecting a bunch of boolean results, we can use `f 0b0011 0b0101` and inspect the `Word` result. That makes it seem more reasonable to `INLINE` the whole thing to specialize to a known function.

```haskell
zipBits
  :: (forall a. Bits a => a -> a -> a)
  -> U.Vector Bit
  -> U.Vector Bit
  -> U.Vector Bit
zipBits f = \xs ys -> case (xs, ys) of
  (BitVec _ 0 _, !_) -> U.empty
  (_, BitVec _ 0 _) -> U.empty
#if UseSIMD
  (BitVec 0 l1 arg1, BitVec 0 l2 arg2) -> runST $ do
    let
        l = noinlineMin l1 l2
        w = nWords l
        b = wordsToBytes w
    brr <- newByteArray b
    case f (0b0011 :: Word) 0b0101 of
     0b0000 -> setByteArray brr 0 w (zeroBits :: Word)
     0b0001 -> ompAnd  brr arg1 arg2 b
     0b0010 -> ompAndn brr arg1 arg2 b
     0b0011 -> copyByteArray brr 0 arg1 0 b
     0b0100 -> ompAndn brr arg2 arg1 b
     0b0101 -> copyByteArray brr 0 arg2 0 b
     0b0110 -> ompXor  brr arg1 arg2 b
     0b0111 -> ompIor  brr arg1 arg2 b
     0b1000 -> ompNior brr arg1 arg2 b
     0b1001 -> ompXnor brr arg1 arg2 b
     0b1010 -> ompCom  brr arg2      b
     0b1011 -> ompIorn brr arg1 arg2 b
     0b1100 -> ompCom  brr arg1      b
     0b1101 -> ompIorn brr arg2 arg1 b
     0b1110 -> ompNand brr arg1 arg2 b
     _0b1111 -> setByteArray brr 0 w (complement zeroBits :: Word)
    BitVec 0 l <$> unsafeFreezeByteArray brr
#endif
  _ -> runST $ do
    let n = noinlineMin (U.length xs) (U.length ys)
    zs <- MU.new n
    forM_ [0, wordSize .. n - 1] $ \i ->
      writeWord zs i (f (indexWord xs i) (indexWord ys i))
    U.unsafeFreeze zs
{-# INLINE zipBits #-}

-- | This is hideous, but it keeps the code size down in applications of
-- 'zipBits'. Otherwise we end up taking different code paths depending
-- on how the comparison goes in the min calculation. Ugh!
noinlineMin :: Int -> Int -> Int
noinlineMin = min
{-# NOINLINE noinlineMin #-}
```

**Comment by treeowl** [comment]
Another option is to forget about inlining, and use `RULES` to specialize to known functions

```haskell
{-# RULES
"this" [~1] forall f. zipBits f = zipBits' (f False False) (f False True) (f True False) (f True True)
"that0000" zipBits' False False False False = ...
"that0001" zipBits' False False False True = ...
...
 #-}

zipBits' :: Bool -> Bool -> Bool -> Bool -> Vector Bit -> Vector Bit -> Vector Bit
zipBits' ff ft tf tt bv1 bv2 = ....
```

Of course, this won't do anything for an *unknown* function, whereas the trick above actually will.

**Comment by Bodigrim** [comment]
TBH I'm not terribly convinced that `forall a. a -> a -> a` is a wrong type. If the bit width is not fixed, `shiftL` and similar are just UB, so `zipWith (whatever using shiftL)` is UB as well, that's fine with me.

**Comment by treeowl** [comment]
I don't think it's terrible to accept a type that doesn't keep things totally safe. I do think that in that case we should us a `Word` wrapper to at least provide a runtime error if someone accidentally does something silly.

**Comment by Bodigrim** [comment]
Retaining `(forall a. Bits a => a -> a -> a)` but internally evaluating `f (0b0011 :: MyWord) 0b0101`, where `instance Bits MyWord` is poisoned for `shiftL` and `popCount`, sounds good to me.
