### ISSUE TITLE
About Thread Safety

### ISSUE THREAD

**Issue by konsumlamm** [Bodigrim/bitvec#78]
What exactly is the goal of the thread-safe operations? I get it for `basicFlipBit` and `basicUnsafeWrite` (they use a single atomic operation to modify the array), but not `modifyByteArray` (it uses two atomic operations, so it can still happen that the array is modified inbetween). Is it undefined behaviour to have multiple concurrent array writes to the same index?

And why are there `Data.Bit.ImmutableTS` and `Data.Bit.F2PolyTS` modules? These only use local mutability, so it shouldn't make a difference wether they use atomics or not (except that the "thread safe" version is slower).

**Comment by Bodigrim** [comment]
When concurrent threads operate on (unaligned) slices of the same array, it's important that they do not mess with each other. (If you do modify the same slice or overlapping slices concurrently then, of course, all bets are off and you are on your own)

Imagine a bit array of size 64, sliced in two halfes, each of which is being inverted via `invertInPlace`. If `modifyByteArray` is implemented as (1) read entire `Word`, (2) modify your slice, (3) write entire `Word` back, and thread A did (1) before thread B, but did (3) after thread B, only one half of the result will be inverted. The thread-safe version of `modifyByteArray` avoids this issue. 

See this test case:
https://github.com/Bodigrim/bitvec/blob/135136ecf53ee225424d692ed2f70ec91336d8b0/test/Tests/Conc.hs#L33-L41

----

> And why are there `Data.Bit.ImmutableTS` and `Data.Bit.F2PolyTS` modules?

`Data.Bit.Bit` and `Data.Bit.ThreadSafe.Bit` are different types, so all machinery must be duplicated.

**Comment by konsumlamm** [comment]
> When concurrent threads operate on (unaligned) slices of the same array, it's important that they do not mess with each other. (If you do modify the same slice or overlapping slices concurrently then, of course, all bets are off and you are on your own)
> 
> Imagine a bit array of size 64, sliced in two halfes, each of which is being inverted via `invertInPlace`. If `modifyByteArray` is implemented as (1) read entire `Word`, (2) modify your slice, (3) write entire `Word` back, and thread A did (1) before thread B, but did (3) after thread B, only one half of the result will be inverted. The thread-safe version of `modifyByteArray` avoids this issue.

Ah, modifying disjoint slices of the same word is a case I hadn't considered, makes sense. Afaict this can still lead to unexpected results when the slices are not disjoint though.

> > And why are there `Data.Bit.ImmutableTS` and `Data.Bit.F2PolyTS` modules?
> 
> `Data.Bit.Bit` and `Data.Bit.ThreadSafe.Bit` are different types, so all machinery must be duplicated.

I see. But `Data.Bit.ImmutableTS` and `Data.Bit.F2PolyTS` use the less efficient thread-safe mutable operations, when they might as well use the non-thread-safe versions. But the two `Bit` types being different means we can't just use the non-thread-safe version, unfortunately. Do you think it would be worth it to duplicate non-thread-safe functions for use in `Data.Bit.ImmutableTS` and `Data.Bit.F2PolyTS`?

**Comment by Bodigrim** [comment]
> Afaict this can still lead to unexpected results when the slices are not disjoint though.

Correct. But one cannot expect operations which affect multiple elements to be atomic. The only thing we care is that the abstraction of slices is uphold. 

> Do you think it would be worth it to duplicate non-thread-safe functions for use in `Data.Bit.ImmutableTS` and `Data.Bit.F2PolyTS`?

That would be quite tedious to implement and more importantly to maintain. It's easy to make a mistake and hard to write good tests. The penalty for `Data.Bit.ThreadSafe` is not that big.

**Comment by konsumlamm** [comment]
> > Afaict this can still lead to unexpected results when the slices are not disjoint though.
> 
> Correct. But one cannot expect operations which affect multiple elements to be atomic. The only thing we care is that the abstraction of slices is uphold.

This might be worth documenting.

**Comment by Bodigrim** [comment]
Sure, feel free to extend the documentation.
