### ISSUE TITLE
WASM build failure

### ISSUE THREAD

**Issue by georgefst** [Bodigrim/bitvec#83]
This probably isn't surprising, given https://github.com/Bodigrim/bitvec/pull/64#discussion_r1148677305:

>> Hmm, wouldn't that break with the JS or WASM backend (or in the rare case that the default C compiler doesn't support OpenMP)?
> 
> I would not worry about them, they are too boutique. Until there is a CI job to witness the contrary, we can effectively assume that they are broken anyways.

```
$ wasm32-wasi-cabal build
Resolving dependencies...
Build profile: -w ghc-9.6.3.20230927 -O1
In order, the following will be built (use -v for more details):
 - bitvec-1.1.5.0 (lib) (first run)
./bitvec.cabal has been changed. Re-configuring with most recently used
options. If this fails, please run configure manually.
Configuring library for bitvec-1.1.5.0..
Preprocessing library for bitvec-1.1.5.0..
Building library for bitvec-1.1.5.0..
[ 9 of 12] Compiling Data.Bit.F2PolyTS ( src/Data/Bit/F2PolyTS.hs, /home/gthomas/code/bitvec/dist-newstyle/build/wasm32-wasi/ghc-9.6.3.20230927/bitvec-1.1.5.0/build/Data/Bit/F2PolyTS.o )

<no location info>: error:
    panic! (the 'impossible' happened)
  GHC version 9.6.3.20230927:
        destination label not in evaluation context
  CallStack (from HasCallStack):
    panic, called at compiler/GHC/Wasm/ControlFlow/FromCmm.hs:303:17 in ghc:GHC.Wasm.ControlFlow.FromCmm


Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

[11 of 12] Compiling Data.Bit.F2Poly  ( src/Data/Bit/F2Poly.hs, /home/gthomas/code/bitvec/dist-newstyle/build/wasm32-wasi/ghc-9.6.3.20230927/bitvec-1.1.5.0/build/Data/Bit/F2Poly.o )

<no location info>: error:
    panic! (the 'impossible' happened)
  GHC version 9.6.3.20230927:
        destination label not in evaluation context
  CallStack (from HasCallStack):
    panic, called at compiler/GHC/Wasm/ControlFlow/FromCmm.hs:303:17 in ghc:GHC.Wasm.ControlFlow.FromCmm


Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug

Error: cabal: Failed to build bitvec-1.1.5.0.
```

This may well be an actual GHC bug, but I thought I'd open it here first in case you have any ideas. Seeing as this is the only library I'm now failing to build in a pretty large dependency tree, and it has some funky C stuff going on.

**Comment by georgefst** [comment]
Ah this looks like a [fixed GHC bug](https://gitlab.haskell.org/ghc/ghc/-/issues/23237), which has not been backported to 9.6. Feel free to close.

Unfortunately I'm relying on GHCup so I can't trivially get hold of a WASM-targeting GHC 9.8. And there's no guarantee that this package's dependencies build on 9.8 yet anyway.

**Comment by Bodigrim** [comment]
Thanks for experimenting!

> And there's no guarantee that this package's dependencies build on 9.8 yet anyway.

FWIW they do.

**Comment by georgefst** [comment]
In fact, GHCup does now ship GHC 9.8 WASM binaries (not sure how I missed that), and I can confirm that this library builds!
