### ISSUE TITLE
request for Hackage release with `tasty` 1.5

### ISSUE THREAD

**Issue by peterbecich** [Bodigrim/bitvec#85]
Can a new release/revision be published including this change: https://github.com/Bodigrim/bitvec/blame/db58eab22e372858e62b9c52925a8bf98b6d14f1/bitvec.cabal#L118

https://hackage.haskell.org/package/bitvec

It will help to build the library on `nixpkgs` in the future.

Thanks

**Comment by Bodigrim** [comment]
Done: https://hackage.haskell.org/package/bitvec-1.1.5.0/revisions/
